spring:
  datasource:
    url: jdbc:mysql://everse-db.cjovcinznjm3.us-east-1.rds.amazonaws.com:3306/everse
    username: admin
    password: admin2023

  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true

application:
  security:
    jwt:
      secret-key: 38782F413F4428472B4B6250655368566D597033733676397924422645294840
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days